service: test-service # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10

functions:
  createTree:
    handler: handler.createTree
    events:
      - sqs: arn:aws:sqs:us-east-1:534322619540:finance-training
