service: test-service # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 250

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: 'www.igna92ts.com'
    basePath: 'finance'
    createRoute53Record: true

functions:
  createTree:
    handler: handler.createTree
    events:
      - http:
          path: create_tree
          method: post
          cors: true 
